baseURL: "http://karthikprabhu.me/"
languageCode: en-us
title: Karthik Prabhu
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: 
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Karthik Prabhu"
    subtitle: Hi 👋 I’m Karthik, a 4th-year medical student at Cambridge. I’ve shared some of my thoughts and experiences here - hope you find them useful, and feel free to connect through my socials below! :)
 
    imageUrl: "home/formalPhoto.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # Featured blog section
  featured:
    enable: true       # turn on featured posts section
    title: "Featured Posts"  # section title
    tag: "featured"    # show posts tagged with "featured"
  
  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:kpp32@cam.ac.uk"
    - name: "linkedin"
      url: "http://linkedin.com/in/karthikprabhu04"
    - name: "instagram"
      url: "https://www.instagram.com/karthikprabhu04/"
    - name: "github"
      url: "https://github.com/karthikprabhu04"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
